version: '3.8'

services:
  be:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "5000:80" # Map the host port 5000 to container port 80 for the .NET Core API

  fe:
    build:
      context: .
      dockerfile: ./FFS.Application/Client/Dockerfile
      args:
        - VITE_FU_FOODY_PUBLIC_API_BASE_URL:${VITE_FU_FOODY_PUBLIC_API_BASE_URL}
        - VITE_FU_FOODY_PUBLIC_API_BASE_URL_UPLOAD_IMAGE:${VITE_FU_FOODY_PUBLIC_API_BASE_URL_UPLOAD_IMAGE}
    ports:
      - "3000:80"
  # Map the host port 3000 to container port 80 for the React app
  # # build app and and use like it, dont need docker file in FE
  # nginx:
  #   image: nginx:alpine
  #   ports: 
  #   - "5050:80"
  #   volumes:
  #     - ./FFS.Application/Client/dist:/usr/share/nginx/html
  #     - ./FFS.Application/Client/nginx.conf:/etc/nginx/conf.d/default.conf
